// Cost of living data for Thai cities (monthly in THB)
// Sources: Numbeo, ExpatDen, ThailandInsiderGuide 2025-2026

export const cities = [
  {
    id: "khon-kaen",
    name: "Khon Kaen",
    region: "Northeast (Isaan)",
    description: "Authentic Thai city with university-quality hospital. Low cost, local vibe, own airport.",
    tags: ["Budget Friendly", "Authentic", "University Hospital"],
    beachAccess: false,
    expatCommunity: "Small",
    distanceBangkok: "450km / 6hr drive",
    costs: {
      rentStudio: 5000,
      rentOneBed: 8500,
      rentTwoBed: 14000,
      foodLocal: 6000,
      foodMixed: 10000,
      foodWestern: 16000,
      utilities: 2500,
      internet: 600,
      transport: 2000,
      entertainment: 4000,
      healthInsurance: 7000,
      misc: 3000,
    },
  },
  {
    id: "hua-hin",
    name: "Hua Hin",
    region: "Gulf Coast",
    description: "Royal beach town with golf courses, strong expat community and great seafood. 2.5hrs from Bangkok.",
    tags: ["Beach", "Golf", "Expat Community"],
    beachAccess: true,
    expatCommunity: "Large",
    distanceBangkok: "200km / 2.5hr drive",
    costs: {
      rentStudio: 8000,
      rentOneBed: 14000,
      rentTwoBed: 22000,
      foodLocal: 8000,
      foodMixed: 13000,
      foodWestern: 20000,
      utilities: 3500,
      internet: 700,
      transport: 3500,
      entertainment: 7000,
      healthInsurance: 7000,
      misc: 4000,
    },
  },
  {
    id: "chiang-mai",
    name: "Chiang Mai",
    region: "Northern Mountains",
    description: "Cultural capital with mountains, temples and a massive digital nomad scene. Excellent value.",
    tags: ["Cultural", "Cool Climate", "Large Expat Scene"],
    beachAccess: false,
    expatCommunity: "Very Large",
    distanceBangkok: "700km / 1hr flight",
    costs: {
      rentStudio: 6000,
      rentOneBed: 10000,
      rentTwoBed: 16000,
      foodLocal: 7000,
      foodMixed: 11000,
      foodWestern: 17000,
      utilities: 3000,
      internet: 650,
      transport: 2500,
      entertainment: 5000,
      healthInsurance: 7000,
      misc: 3500,
    },
  },
  {
    id: "phuket",
    name: "Phuket",
    region: "Andaman Coast",
    description: "World-famous island with stunning beaches. More expensive but exceptional lifestyle and infrastructure.",
    tags: ["Island", "Beach", "International"],
    beachAccess: true,
    expatCommunity: "Very Large",
    distanceBangkok: "860km / 1.5hr flight",
    costs: {
      rentStudio: 12000,
      rentOneBed: 18000,
      rentTwoBed: 30000,
      foodLocal: 9000,
      foodMixed: 15000,
      foodWestern: 24000,
      utilities: 4000,
      internet: 800,
      transport: 4500,
      entertainment: 10000,
      healthInsurance: 7000,
      misc: 5000,
    },
  },
  {
    id: "pattaya",
    name: "Pattaya",
    region: "Eastern Seaboard",
    description: "Affordable beach city 90 mins from Bangkok. Huge expat scene, great infrastructure, budget friendly.",
    tags: ["Beach", "Budget", "Bangkok Proximity"],
    beachAccess: true,
    expatCommunity: "Very Large",
    distanceBangkok: "150km / 1.5hr drive",
    costs: {
      rentStudio: 7000,
      rentOneBed: 11000,
      rentTwoBed: 18000,
      foodLocal: 7500,
      foodMixed: 12000,
      foodWestern: 18000,
      utilities: 3200,
      internet: 650,
      transport: 2500,
      entertainment: 7000,
      healthInsurance: 7000,
      misc: 3500,
    },
  },
  {
    id: "bangkok",
    name: "Bangkok",
    region: "Central Thailand",
    description: "World-class city with the best hospitals, food, transport and nightlife. Higher cost, unmatched convenience.",
    tags: ["City Life", "World-Class Hospitals", "BTS/MRT"],
    beachAccess: false,
    expatCommunity: "Very Large",
    distanceBangkok: "—",
    costs: {
      rentStudio: 10000,
      rentOneBed: 18000,
      rentTwoBed: 28000,
      foodLocal: 8000,
      foodMixed: 14000,
      foodWestern: 22000,
      utilities: 3500,
      internet: 700,
      transport: 3000,
      entertainment: 8000,
      healthInsurance: 7000,
      misc: 4500,
    },
  },
];

// Australian pension rates (March 2026)
export const pensionRates = {
  single: {
    fortnightly: 1200.90,
    weekly: 600.45,
    annual: 31223,
    overseasWeekly: 550, // Approximate after losing supplements
    overseasFortnightly: 1100,
  },
  couple: {
    fortnightlyEach: 905.20,
    weeklyEach: 452.60,
    annualEach: 23535,
    combined: {
      fortnightly: 1810.40,
      weekly: 905.20,
      annual: 47070,
    },
  },
};

export const lifestyleOptions = [
  { id: "budget", label: "Budget", description: "Mostly street food, basic condo, local transport", multiplier: 0.75 },
  { id: "comfortable", label: "Comfortable", description: "Nice condo, mix of dining, some Western comforts", multiplier: 1.0 },
  { id: "western", label: "Western Comforts", description: "Imported food, modern condo, car or regular taxis", multiplier: 1.4 },
];

export const rentOptions = [
  { id: "studio", label: "Studio / 1 Room", key: "rentStudio" },
  { id: "one-bed", label: "1 Bedroom Condo", key: "rentOneBed" },
  { id: "two-bed", label: "2 Bedroom Condo", key: "rentTwoBed" },
];

export const foodOptions = [
  { id: "local", label: "Mostly Local Thai", key: "foodLocal" },
  { id: "mixed", label: "Mix of Thai & Western", key: "foodMixed" },
  { id: "western", label: "Mostly Western", key: "foodWestern" },
];
