// Cost of living data for Thai cities (monthly in THB)
// Sources: Numbeo, ExpatDen, ThailandInsiderGuide 2025-2026
// v2 — added pensionRates for AUD, USD, GBP, CAD

export const cities = [
  {
    id: "khon-kaen",
    name: "Khon Kaen",
    region: "Northeast (Isaan)",
    description: "Authentic Thai city with university-quality hospital. Low cost, local vibe, own airport.",
    tags: ["Budget Friendly", "Authentic", "University Hospital"],
    beachAccess: false,
    expatCommunity: "Small",
    distanceBangkok: "450km / 6hr drive",
    costs: {
      rentStudio: 5000,
      rentOneBed: 8500,
      rentTwoBed: 14000,
      rentTownhouse: 10000,
      rentHousePool: 18000,
      foodLocal: 6000,
      foodMixed: 10000,
      foodWestern: 16000,
      utilities: 2500,
      internet: 600,
      transport: 2000,
      entertainment: 4000,
      healthInsurance: 7000,
      misc: 3000,
    },
  },
  {
    id: "hua-hin",
    name: "Hua Hin",
    region: "Gulf Coast",
    description: "Royal beach town with golf courses, strong expat community and great seafood. 2.5hrs from Bangkok.",
    tags: ["Beach", "Golf", "Expat Community"],
    beachAccess: true,
    expatCommunity: "Large",
    distanceBangkok: "200km / 2.5hr drive",
    costs: {
      rentStudio: 8000,
      rentOneBed: 14000,
      rentTwoBed: 22000,
      rentTownhouse: 18000,
      rentHousePool: 30000,
      foodLocal: 8000,
      foodMixed: 13000,
      foodWestern: 20000,
      utilities: 3500,
      internet: 700,
      transport: 3500,
      entertainment: 7000,
      healthInsurance: 7000,
      misc: 4000,
    },
  },
  {
    id: "chiang-mai",
    name: "Chiang Mai",
    region: "Northern Mountains",
    description: "Cultural capital with mountains, temples and a massive digital nomad scene. Excellent value.",
    tags: ["Cultural", "Cool Climate", "Large Expat Scene"],
    beachAccess: false,
    expatCommunity: "Very Large",
    distanceBangkok: "700km / 1hr flight",
    costs: {
      rentStudio: 6000,
      rentOneBed: 10000,
      rentTwoBed: 16000,
      rentTownhouse: 12000,
      rentHousePool: 22000,
      foodLocal: 7000,
      foodMixed: 11000,
      foodWestern: 17000,
      utilities: 3000,
      internet: 650,
      transport: 2500,
      entertainment: 5000,
      healthInsurance: 7000,
      misc: 3500,
    },
  },
  {
    id: "phuket",
    name: "Phuket",
    region: "Andaman Coast",
    description: "World-famous island with stunning beaches. More expensive but exceptional lifestyle and infrastructure.",
    tags: ["Island", "Beach", "International"],
    beachAccess: true,
    expatCommunity: "Very Large",
    distanceBangkok: "860km / 1.5hr flight",
    costs: {
      rentStudio: 12000,
      rentOneBed: 18000,
      rentTwoBed: 30000,
      rentTownhouse: 25000,
      rentHousePool: 45000,
      foodLocal: 9000,
      foodMixed: 15000,
      foodWestern: 24000,
      utilities: 4000,
      internet: 800,
      transport: 4500,
      entertainment: 10000,
      healthInsurance: 7000,
      misc: 5000,
    },
  },
  {
    id: "pattaya",
    name: "Pattaya",
    region: "Eastern Seaboard",
    description: "Affordable beach city 90 mins from Bangkok. Huge expat scene, great infrastructure, budget friendly.",
    tags: ["Beach", "Budget", "Bangkok Proximity"],
    beachAccess: true,
    expatCommunity: "Very Large",
    distanceBangkok: "150km / 1.5hr drive",
    costs: {
      rentStudio: 7000,
      rentOneBed: 11000,
      rentTwoBed: 18000,
      rentTownhouse: 15000,
      rentHousePool: 28000,
      foodLocal: 7500,
      foodMixed: 12000,
      foodWestern: 18000,
      utilities: 3200,
      internet: 650,
      transport: 2500,
      entertainment: 7000,
      healthInsurance: 7000,
      misc: 3500,
    },
  },
  {
    id: "bangkok",
    name: "Bangkok",
    region: "Central Thailand",
    description: "World-class city with the best hospitals, food, transport and nightlife. Higher cost, unmatched convenience.",
    tags: ["City Life", "World-Class Hospitals", "BTS/MRT"],
    beachAccess: false,
    expatCommunity: "Very Large",
    distanceBangkok: "—",
    costs: {
      rentStudio: 10000,
      rentOneBed: 18000,
      rentTwoBed: 28000,
      rentTownhouse: 22000,
      rentHousePool: 45000,
      foodLocal: 8000,
      foodMixed: 14000,
      foodWestern: 22000,
      utilities: 3500,
      internet: 700,
      transport: 3000,
      entertainment: 8000,
      healthInsurance: 7000,
      misc: 4500,
    },
  },
  {
    id: "chiang-rai",
    name: "Chiang Rai",
    region: "Far North",
    description: "Peaceful border town with low costs, stunning temples and a growing expat community. Thailand's best kept secret.",
    tags: ["Peaceful", "Budget", "Cultural"],
    beachAccess: false,
    expatCommunity: "Small",
    distanceBangkok: "850km / 1hr flight",
    costs: {
      rentStudio: 4500,
      rentOneBed: 7500,
      rentTwoBed: 12000,
      rentTownhouse: 9000,
      rentHousePool: 16000,
      foodLocal: 5500,
      foodMixed: 9000,
      foodWestern: 14000,
      utilities: 2200,
      internet: 600,
      transport: 2000,
      entertainment: 3500,
      healthInsurance: 7000,
      misc: 2500,
    },
  },
];

// Australian pension rates (March 2026)
export const pensionRates = {
  AUD: {
    single: {
      overseasWeekly: 550,
      overseasFortnightly: 1100,
      label: 'Single overseas rate · March 2026',
      note: null,
    },
    couple: {
      weekly: 905.20,
      label: 'Couple combined · March 2026',
      note: null,
    },
  },
  GBP: {
    single: {
      overseasWeekly: 241.30,
      overseasFortnightly: 482.60,
      label: 'UK Full New State Pension · 2026/27',
      note: 'Full rate — requires 35 NI years',
    },
    couple: {
      weekly: 482.60,
      label: 'UK State Pension couple · 2026/27',
      note: 'Two full state pensions combined',
    },
  },
  CAD: {
    single: {
      overseasWeekly: 363,
      overseasFortnightly: 726,
      label: 'Average CPP + OAS combined · 2026',
      note: 'Average',
    },
    couple: {
      weekly: 726,
      label: 'Average CPP + OAS couple · 2026',
      note: 'Average — two recipients',
    },
  },
    single: {
      overseasWeekly: 480,
      overseasFortnightly: 960,
      label: 'US Social Security · 2026',
      note: 'Average',
    },
    couple: {
      weekly: 784,
      label: 'US Social Security couple · 2026',
      note: 'Average',
    },
  };


export const lifestyleOptions = [
  { id: "budget", label: "Budget", description: "Mostly street food, basic condo, local transport", multiplier: 0.75 },
  { id: "comfortable", label: "Comfortable", description: "Nice condo, mix of dining, some Western comforts", multiplier: 1.0 },
  { id: "western", label: "Western Comforts", description: "Imported food, modern condo, car or regular taxis", multiplier: 1.4 },
];

export const rentOptions = [
  { id: "studio",        label: "Studio / 1 Room",          key: "rentStudio" },
  { id: "one-bed",       label: "1 Bedroom Condo",          key: "rentOneBed" },
  { id: "two-bed",       label: "2 Bedroom Condo",          key: "rentTwoBed" },
  { id: "townhouse",     label: "Townhouse",                 key: "rentTownhouse" },
  { id: "house-pool",    label: "2 Bed House with Pool",     key: "rentHousePool" },
];

export const foodOptions = [
  { id: "local",   label: "Mostly Local Thai",    key: "foodLocal" },
  { id: "mixed",   label: "Mix of Thai & Western", key: "foodMixed" },
  { id: "western", label: "Mostly Western",        key: "foodWestern" },
];
